micronaut:
  application:
    name: DemoApplication

  # server static content from folder called 'public' in the JAR
  router.static-resources.default:
    enabled: true
    paths: "classpath:public"
    mapping: "/**"    

  server:
    port: 8082
    cors:
      enabled: true # so that the static resources can be served from another origin  
      
  security:
    enabled: true
    authentication: idtoken 
    oauth2:
      clients:
        my-okta-app: # The provider identifier 
          openid:
            issuer: https://dev-73627270.okta.com/oauth2/default
    token:
      # must be the same name as the role "claim" created in Okta for app user roles.        
      # now the myRole claim is automatically mapped to the roles attrbute in Micronaut's 
      # io.micronaut.security.authentication.Authentication
      # Micronaut automatically maps all 'groups' claim entries to corresponding roles
      roles-name: myRole 
    
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    schema-generate: CREATE_DROP
    dialect: H2
    
    
#datasources:
#  default:
#    url: jdbc:mysql://localhost:3306/app-db
#    username: app-db-user
#    password: 'my-password'
#    driverClassName: com.mysql.cj.jdbc.Driver
#    schema-generate: CREATE
#    db-type: mysql
#    dialect: org.hibernate.dialect.MySQL8Dialect
    #hikari
#    leakDetectionThreshold: 20000 # Warn when a connections is kept out of the pool for more than 20 seconds.
#    pool-name: hikari-read-write
#    maximum-pool-size: 10
#    read-only: false
#    data-source-properties:
#      cachePrepStmts: true
#      enabledTLSProtocols: TLSv1.2
#      prepStmtCacheSize: 250
#      prepStmtCacheSqlLimit: 2048
#      requireSSL: true
#      useSSL: true
#      useServerPrepStmts: true
#      verifyServerCertificate: false


jpa:
  default:
    entity-scan:
      packages: com.example.demo.book
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: false
        format_sql: true
    
    

netty:
  default:
    allocator:
      max-order: 3
